### ISSUE TITLE
Unable to login to Omada 5.7.4

### ISSUE THREAD

**Issue by builder555** [ghaberek/omada-api#11]
### Steps to reproduce:

* clone repo
* run `pip -r requirements.txt`
* create omada.cfg (with proper credentials)
* copy sample code to demo.py
* `python demo.py`

### Expected results:
LED turns off

### Actual results:
```
Traceback (most recent call last):
  File "/Users/main/dev/omada-api/demo.py", line 10, in <module>
    omada.login()
  File "/Users/main/dev/omada-api/omada/omada.py", line 242, in login
    result = self.post( '/login', json={'username':username,'password':password} )
  File "/Users/main/dev/omada-api/omada/omada.py", line 203, in post
    response.raise_for_status()
  File "/Users/main/dev/omada-api/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://192.168.0.100:8043/api/v2/login?_=1673422789425
```

**Comment by builder555** [comment]
update: i added the controller UUID to the baseurl, now the error is different: getCurrentUser method is getting HTML instead of JSON. i see the token is set after POST `/login`.

**Comment by kdpuvvadi** [comment]
i've appended controller id to the url 
previous `https://omada.puvvadi.me`
new `https://omada.puvvadi.net/${siteid}` 
now getting another error 

```shell
$ python3 clients.py
Traceback (most recent call last):
  File "/home/kd/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kd/omada-api/clients.py", line 113, in <module>
    main()
  File "/home/kd/omada-api/clients.py", line 98, in main
    omada.login()
  File "/home/kd/omada-api/omada/omada.py", line 244, in login
    self.currentUser = self.getCurrentUser()
  File "/home/kd/omada-api/omada/omada.py", line 263, in getCurrentUser
    return self.get( '/users/current' )
  File "/home/kd/omada-api/omada/omada.py", line 163, in get
    json = response.json()
  File "/home/kd/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kdpuvvadi** [comment]
#5 seems to fix this issue

just tested this and works fine.

**Comment by kdpuvvadi** [comment]
```
$ gh pr checkout 5
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 16 (delta 8), reused 13 (delta 5), pack-reused 0
Unpacking objects: 100% (16/16), 1.93 KiB | 164.00 KiB/s, done.
From https://github.com/ghaberek/omada-api
 * [new ref]         refs/pull/5/head -> sreggy/main
Switched to branch 'sreggy/main'
$ python3 clients.py
USERNAME            IP ADDRESS      STATUS      NETWORK     PORT            ACTIVITY    DOWNLOAD  UPLOAD    UPTIME
OC200               192.168.0.3     CONNECTED   LAN         Main Switch ... 1.5 KB/s    9.7 MB    16.7 MB   2:52:53
AP_C1200            10.20.20.102    CONNECTED   LAN20       Main Switch ... 0.8 KB/s    4.5 GB    172.2 MB  2:53:20
odin                10.20.20.23     CONNECTED   LAN20       Main Switch ... 0.8 KB/s    28.0 MB   28.4 MB   2:52:08
```

**Comment by builder555** [comment]
#5 fixed this. I just have to put URL without the UUID.
